--
-- USER SQL
CREATE USER "MYSTUDY" IDENTIFIED BY "MYSTUDYPW"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"


-- QUOTAS

-- ROLES
ALTER USER "MYSTUDY" DEFAULT ROLE "CONNECT","RESOURCE";

-- SYSTEM PRIVILEGES