/*함수(FUNCTION) ***************
CREATE OR REPLACE FUNCTION FUNCTION1 (
  PARAM1 IN VARCHAR2 --파라미터 (옵션)
) RETURN VARCHAR2  --리턴 데이터 타입 선언(필수)
AS
BEGIN
  RETURN NULL; ---리턴값(필수)
END;
----------------
--리턴 데이터 타입 선언 필요
RETURN 데이터 유형

--프로그램 마지막 (중간)에 값 리턴하는 RETURN문 필요(필수)
RETURN 리턴값;

***********************/
--BOOKID로 책제목 확인 함수 (파라미터 값: BOOKID, RETURN값: BOOKNAME)
CREATE OR REPLACE FUNCTION GET_BOOKNAME (
    IN_ID IN NUMBER
) RETURN VARCHAR2 --리턴데이터 타입
AS
    V_BOOKNAME BOOK.BOOKNAME%TYPE;
BEGIN
    SELECT BOOKNAME 
    INTO V_BOOKNAME
    FROM BOOK
    WHERE BOOKID = IN_ID;
    
    RETURN V_BOOKNAME;
END;
--------------------
--함수의 사용(SELECT, WHERE 절에서 사용)
--동작여부 확인
SELECT GET_BOOKNAME(5) FROM DUAL;
--SELECT 절에서 사용
SELECT BOOKID, BOOKNAME, GET_BOOKNAME(BOOKID)
FROM BOOK;
----------
SELECT O.*, GET_BOOKNAME(BOOKID)
FROM ORDERS O;
---------
-- WHERE 절에서 함수 사용
SELECT O.*
     , GET_BOOKNAME(O.BOOKID) AS BOOKNAME
FROM ORDERS O
WHERE GET_BOOKNAME(O.BOOKID) LIKE '%야구%'
;
--=========================
--(실습) 고객ID 값을 받아서 고객명을 돌려주는 함수 작성(CUSTOMER 테이블 사용)
-- 함수명 : GET_CUSTNAME
-- GET_CUSTNAME 함수 사용해서 고객명 검색 여부 확인해보기
-------------------
-- ORDERS 테이블 데이터 조회
---- GET_BOOKNAME, GET_CUSTNAME 함수사용 주문(판매)정보와 책제목, 고객명 조회
---------------------

CREATE OR REPLACE FUNCTION GET_CUSTNAME(
    IN_ID IN NUMBER
) RETURN VARCHAR2
AS V_NAME CUSTOMER.NAME%TYPE;
BEGIN 
    SELECT NAME   
    INTO V_NAME
    FROM CUSTOMER
    WHERE CUSTID = IN_ID;
    
    RETURN V_NAME;
END;

SELECT GET_CUSTNAME(2) FROM DUAL;

SELECT O.*, GET_CUSTNAME(O.CUSTID)
FROM ORDERS O
;

SELECT O.*, GET_BOOKNAME(O.BOOKID), GET_CUSTNAME(O.CUSTID)
FROM ORDERS O;
-------------------
SELECT O.*
     , (SELECT BOOKNAME FROM BOOK WHERE BOOKID = O.BOOKID) AS BOOK_NAME
     , (SELECT NAME FROM CUSTOMER WHERE CUSTID = O.CUSTID) AS CUST_NAME
FROM ORDERS O
;
-----------
SELECT O.*
     , B.BOOKNAME
     , C.NAME
FROM ORDERS O, BOOK B, CUSTOMER C
WHERE O.BOOKID = B.BOOKID
  AND O.CUSTID = C.CUSTID
;
