SELECT ABS(-15)FROM DUAL; --절대값 반환
SELECT CEIL(15.7)FROM DUAL; --소수점 올림
SELECT COS(3.14159)FROM DUAL; --코사인 값
SELECT FLOOR(15.7)FROM DUAL;--소수점 내림
SELECT LOG(10,100)FROM DUAL;
SELECT MOD(11,4)FROM DUAL; --나머지 값
SELECT POWER(3,2)FROM DUAL;
SELECT ROUND(15.7)FROM DUAL; --반올림 (수, 반올림할 소수점 자리)
SELECT SIGN(-15)FROM DUAL; --음수 양수 판단. 음수:-1 양수 :1
SELECT TRUNC(15.7)FROM DUAL; -- 지정 소수점 버림
SELECT CHR(67)FROM DUAL;
SELECT CONCAT('HAPPY', 'BIRTHDAY')FROM DUAL;
SELECT LOWER('Birthday')FROM DUAL;
SELECT LPAD('Page 1', 15, '*.')FROM DUAL;
SELECT LTRIM('Page 1','ae')FROM DUAL; -- 공백제거 OR 문자열 제거 
SELECT REPLACE('JACK', 'J', 'BL')FROM DUAL;
SELECT RPAD('Page 1', 15, '*.')FROM DUAL;
SELECT SUBSTR('ABCDEFG', 3, 4)FROM DUAL;
SELECT TRIM(LEADING 0 FROM '00AA00')FROM DUAL; --공백제거 OR 문자열 제거  LEADING(왼쪽에서 제거) , TRAILING(오른쪽에서 제거) , BOTH(양쪽에서제거)
SELECT UPPER('Birthday')FROM DUAL;
SELECT ASCII('C')FROM DUAL;
SELECT INSTR('CORPORATE FLOOR','OR',3,2)FROM DUAL; --문자열에서 문자 위치 찾기 ('문자열', '찾을 문자', 시작위치, 값이 중복일 경우 찾을 문자 위치 선택)
SELECT LENGTH('Birthday')FROM DUAL;
SELECT ADD_MONTHS('14/05/21', 1)FROM DUAL; -- 달 추가
SELECT LAST_DAY(SYSDATE)FROM DUAL; --해당 월의 마지막 날 반환
SELECT NEXT_DAY(SYSDATE,'화')FROM DUAL; --NEXT_DAY (날짜, '요일' or 숫자) 돌아오는 날짜 반환
SELECT ROUND(SYSDATE)FROM DUAL;
SELECT SYSDATE FROM DUAL;
SELECT TO_CHAR (SYSDATE)FROM DUAL;
SELECT TO_CHAR (123)FROM DUAL;
SELECT TO_DATE ('12 05 2014', 'DD MM YYYY')FROM DUAL;
SELECT TO_NUMBER ('12.3')FROM DUAL;
SELECT DECODE (1, 1, 'aa', 'bb')FROM DUAL; --ex DECODE( COLUMN1, '1', '예', '2', '아니오') 컬럼과 조건의 값이 동일하면 예 출력 아니면 아니오 출력
SELECT NULLIF (123,345)FROM DUAL; --두 개의 값이 동일하면 NULL로 치환한다. 다르면 첫번째 값을 반환












